require_relative "./movie_seeker/version"
require_relative "./movie_seeker/cli"
require_relative "./movie_seeker/scraper"
require_relative "./movie_seeker/in_theater"
require_relative "./movie_seeker/coming_soon"
